plugins {
    id 'com.android.application'
}

android {
    namespace 'com.m19.hdrtoggle'
    compileSdk 33

    defaultConfig {
        applicationId "com.m19.hdrtoggle"
        minSdk 21
        targetSdk 28 // 保持 28 避免高版本明文 Socket 限制
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    // 禁用 Lint 检查阻断构建
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'com.github.cgutman:adblib:master-SNAPSHOT'
}
